deploy:
  stage: deploy
  tags:
    - ewsfrontend
  only:
    - main
  image: docker:latest
  services:
    - docker:dind
  script:
    - rm -rf dist node_modules
    - docker ps -a
    - ls
    - docker build -t cdi_main .
    - docker stop cdi_main_container || true
    - docker rm cdi_main_container || true
    - docker run -d -p 3000:80 --add-host=host.docker.internal:host-gateway --restart unless-stopped --name cdi_main_container cdi_main
   