name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          echo "Checking secrets..."
          if [ -z "${{ secrets.GITLAB_USERNAME }}" ]; then echo "USERNAME missing"; exit 1; fi
          if [ -z "${{ secrets.GITLAB_TOKEN }}" ]; then echo "TOKEN missing"; exit 1; fi
          if [ -z "${{ secrets.GITLAB_REPO }}" ]; then echo "REPO missing"; exit 1; fi
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_REPO }}.git
          git push gitlab main --force
